apiVersion: v1
appVersion: "1.0"
name: dbs-admin
description: Admin Manager for SQL and No-SQL Databases
version: 0.1.0
kubeVersion: ">=1.2.0"
keywords:
  - sql
  - nosql
  - phpmyadmin
  - mongo-express
  - storage-nfs
  - storage-local
  - storage-temp
maintainers:
  - name: David Palmero
    url: https://github.com/palmiot
