apiVersion: v1
kind: Service
metadata:
  name: sql-{{ .Values.name }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: socket
  selector:
    app: sql-{{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: sql-web-{{ .Values.name }}
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ .Values.panels.sql.port }}
    protocol: TCP
    name: http
  selector:
    app: sql-web-{{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: nosql-{{ .Values.name }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: socket
  selector:
    app: nosql-{{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: nosql-web-{{ .Values.name }}
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: {{ .Values.panels.nosql.port }}
    protocol: TCP
    name: http
  selector:
    app: nosql-web-{{ .Values.name }}
